Switched from string table name to Arel::Table for build_relation
Was getting this exception:

  1) Error:
test_should_validate_without_deleted(ValidatesUniquenessTest):
TypeError: can't convert Symbol into Integer
    /Users/craig/.rvm/gems/ruby-1.9.2-p0@paranoid/gems/activerecord-3.1.3/lib/active_record/validations/uniqueness.rb:65:in `[]'
    /Users/craig/.rvm/gems/ruby-1.9.2-p0@paranoid/gems/activerecord-3.1.3/lib/active_record/validations/uniqueness.rb:65:in `build_relation'
    /Users/craig/Sites/rails3_acts_as_paranoid/lib/validations/uniqueness_without_deleted.rb:13:in `validate_each'
    ...

In addition to the rename, build_relation is now also expecting a Arel::Table.
It then extracts the field using table[attribute].
When table was a String, the dereferencing was expecting an integer array index.